name = "publicsuffix_gleam"
version = "1.0.0"
description = "Parse domain names into component parts using the Public Suffix List"
licences = ["Apache-2.0"]
repository = { type = "github", user = "cassiascheffer", repo = "publicsuffix_gleam" }


[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
idna = ">= 6.0.0 and < 7.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
